### ISSUE TITLE
Host pattern not allows dash character

### ISSUE THREAD

**Issue by dfadid** [swagger-api/swagger-editor#1033]
**Swagger File**
hey , 
I want to add my host to the swagger json but it doesnt match the pttern.
is this the expected behavior? 
```yaml
  Swagger Error

The host (name or ip) of the API. Example: 'swagger.io'
Jump to line 0
Details
Object
code: "PATTERN"
params: Array [2]
0: "^[^{}/ :\\]+(?::\d+)?$"
1: "host-a:8080/"
message: "String does not match pattern ^[^{}/ :\\]+(?::\d+)?$: host-a:8080/"
path: Array [1]
0: "host"
schemaId: "http://swagger.io/v2/schema.json#"
description: "The host (name or ip) of the API. Example: 'swagger.io'"
level: 900
type: "Swagger Error"
lineNumber: 0

```
