### ISSUE TITLE
`type: file` is not recognized in a ref schema

### ISSUE THREAD

**Issue by akauppi** [swagger-api/swagger-editor#1040]
While `type: file` seems to be recognized if directly under `schema`, it's still not usable behind a reference. e.g.

```
definitions:
  testHtml:
    description: |
      Sample content
    type: file
    format: text/html
```

The error:

```
ENUM_MISMATCH
message:  "No enum match for: file"
```

Swagger Editor 2.10.2

Also mentioned [here](https://github.com/OAI/OpenAPI-Specification/issues/260).
