### ISSUE TITLE
Example for XML Attribute property in specification

### ISSUE THREAD

**Issue by Shruti-R** [swagger-api/swagger-editor#1058]
**Swagger File**

``` yaml
 Person:
  type: object
  properties:
    id:
      type: integer
      format: int32
      xml:
        attribute: true
    name:
      type: string
      xml:
        namespace: http://swagger.io/schema/sample
        prefix: sample
```
- Version: 
- Browser/OS: 

**Issue**
I found specification for XML Attribute, Prefix and Namespace in [specification](http://swagger.io/specification/) and wanted to try something similar; but could not find example for the same in [swagger editor](http://editor.swagger.io/).
