### ISSUE TITLE
Swagger Editor doesn't check if the example is empty.

### ISSUE THREAD

**Issue by franciszabala** [swagger-api/swagger-editor#1080]
Swagger Editor doesn't check if the example is empty.

```
  SearchContactRequest:
    type: object
    properties:
      first_name:
        type: string
        description: First name of the subscriber
      last_name:
        type: string
        description: Last name of the subscriber
    required:
      - first_name
      - last_name
    example:
      first_name: Andrew
      last_name: 
```

The editor does not mark it as an error or warn user that it is empty.

If the yml is loaded, Swagger-ui won't process the yml

This is the error on the browser:
`
TypeError: Swagger 2.0 does not support null types ([object Object]).  See https://github.com/swagger-api/swagger-spec/issues/229.`
