### ISSUE TITLE
How to get response of GET request of my own Rest-api on swagger ui

### ISSUE THREAD

**Issue by Dhvanish1299** [swagger-api/swagger-editor#1097]
- I am new to use swagger ui, Kindly please help me to generate response of my rest-api in swagger ui.
- My Restapi server running on http://localhost:8610.
- Swagger ui running on http://localhost:8080.

 Below steps i have followed: 
- **Step 1:** I have download swagger ui latest code 2.2.6.
- **Step 2:** I have setup all things in my system - node, npm, node.js and run npm run serve to start server.
- **Step 3 :** Create file swagger.json at dist and write my client code at swagger editor and test it and save it in dist/swagger.json .
- **Step 4:** My rest-api server running at 8610  and I have Tryout swagger ui as client but unable to get response at swagger ui.(Request sent to server(8610) and it respond but not get response in ui(8080))
- I have modified dist/index.html file as:  "url" = "/swagger.json"
- I have attached my swagger ui swagger.json file code here.

**Swagger File**

```yaml
 {
"swagger": "2.0",
"info": {
"version": "1.0.0",
"title": "REST-API",
"license": {
"name": "Dhvanish"
}
},
"host":"localhost:8610",
"basePath": "/api/v1/",
"schemes": [
"http"
],
"consumes": [
"application/json",
"image/jpeg"
],
"produces": [
"application/json",
],
"paths": {
"/server/{username}/{albumname}/{imagename}": {
"get": {
"summary": "Info for a specific get image",
"operationId": "getImage",
"tags": [
"server"
],
"parameters": [
{
"name": "username",
"in": "path",
"required": true,
"description": "username is required for server",
"type": "string"
},
{
"name": "albumname",
"in": "path",
"required": true,
"description": "albumname required for server",
"type": "string"
},
{
"name": "imagename",
"in": "path",
"required": true,
"description": "albumname required for server",
"type": "string"
}
],
"responses": {
"200": {
"description": "Expected response to a valid request",
"schema": {
"$ref": "#/definitions/responseCode"
}
},
"default": {
"description": "unexpected error",
"schema": {
"$ref": "#/definitions/Error"
}
}
}
}
}
},
"definitions": {
"responseCode": {
"type": "object",
"required": [
"status",
"userid",
"data"
],
"properties": {
"status": {
"type": "string",
"format": "string"
},
"userid": {
"type": "integer",
"format": "int64"

            },
            "data": {
                "type": "array",
                "items": {
                 "$ref": "#/definitions/responseCode"
                }

            }
        }
    },
"Error": {
  "required": [
    "code",
    "message"
  ],
  "properties": {
    "code": {
      "type": "integer",
      "format": "int32"
    },
    "message": {
      "type": "string"
    }
  }
}
}
```

* Version: swagger ui 2.2.6
* Browser/OS:  chrome/firefox - xubantu 14.04

**Issue** : Not getting response at swagger ui http://localhost:8080.
- I have checked my url : http://localhost:8610/api/v1/server/username/albumname/imagename gives perfect response in browser(chromw/firefox) but i am not getting this response in swagger ui at http://localhost:8080 where my swagger ui waiting for response .
-Please, Help me how can i get response at http:localhist:8080 of my rest api response..

@mohsen1  @fehguy  @saharj  @joelparkerhenderson
