### ISSUE TITLE
"Equivalent path already exists" with different methods

### ISSUE THREAD

**Issue by seven7cx** [swagger-api/swagger-editor#1104]
**Swagger File**

 # paste your swagger document here
```yaml
{
    "swagger": "2.0",
    "info": {
        "title": "云通讯用户管理后台",
        "description": "云通讯Server Http API接口文档",
        "version": "1.0.0"
    },
    "host": "ucenter.glodon.com",
    "schemes": [
        "http"
    ],
    "basePath": "/",
    "produces": [
        "application/json"
    ],
    "paths": {
        "/oauth2/token": {
            "post": {
                "summary": "获取token",
                "description": "通过应用名称和应用唯一标识(appKey)换取token\n返回值包含token、refreshToken及其有效期\n",
                "parameters": [
                    {
                        "name": "app_name",
                        "in": "query",
                        "description": "应用名称.",
                        "required": true,
                        "type": "string",
                        "format": "string"
                    },
                    {
                        "name": "app_key",
                        "in": "query",
                        "description": "应用唯一标识.",
                        "required": true,
                        "type": "string",
                        "format": "string"
                    }
                ],
                "tags": [
                    "token"
                ],
                "responses": {
                    "200": {
                        "description": "json格式的token、refreshToken及其有效期",
                        "schema": {
                            "$ref": "#/definitions/BaseResponse-Token"
                        }
                    },
                    "401": {
                        "description": "Unexpected error，Basic认证未通过"
                    }
                }
            }
        },
        "/oauth2/{company_key}/{app_name}/token/{refresh_token}": {
            "get": {
                "summary": "刷新token",
                "description": "token过期时通过refreshToken换取新的token\n",
                "parameters": [
                    {
                        "name": "company_key",
                        "in": "path",
                        "description": "公司唯一标识",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "app_name",
                        "in": "path",
                        "description": "应用名称",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "refresh_token",
                        "in": "path",
                        "required": true,
                        "type": "string"
                    }
                ],
                "tags": [
                    "token"
                ],
                "responses": {
                    "200": {
                        "description": "json格式的token、refreshToken及其有效期",
                        "schema": {
                            "$ref": "#/definitions/BaseResponse-Token"
                        }
                    },
                    "401": {
                        "description": "Unexpected error，Basic认证未通过"
                    }
                }
            }
        },
        "/oauth2/verify": {
            "post": {
                "summary": "验证token是否有效",
                "parameters": [
                    {
                        "name": "companyKey",
                        "in": "query",
                        "description": "公司唯一标识.",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "appName",
                        "in": "query",
                        "description": "应用名称.",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "bearer",
                        "in": "query",
                        "type": "string",
                        "description": "token值."
                    }
                ],
                "tags": [
                    "token"
                ],
                "responses": {
                    "200": {
                        "description": "json格式的token、refreshToken及其有效期",
                        "schema": {
                            "$ref": "#/definitions/BaseResponse"
                        }
                    },
                    "401": {
                        "description": "Unexpected error，Basic认证未通过"
                    }
                }
            }
        },
        "/oauth2/token/{app_key}": {
            "delete": {
                "summary": "登出",
                "description": "登出后系统将会删除token和refreshToken.",
                "tags": [
                    "token"
                ],
                "parameters": [
                    {
                        "name": "app_key",
                        "in": "path",
                        "description": "应用唯一标识.",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "json格式的token、refreshToken及其有效期",
                        "schema": {
                            "$ref": "#/definitions/BaseResponse"
                        }
                    },
                    "401": {
                        "description": "Unexpected error，Basic认证未通过"
                    }
                }
            }
        },
        "/{company_key}/{app_name}/users": {
            "post": {
                "summary": "批量创建用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "company_key",
                        "in": "path",
                        "type": "string",
                        "required": true
                    },
                    {
                        "name": "app_name",
                        "in": "path",
                        "type": "string",
                        "required": true
                    },
                    {
                        "name": "userList",
                        "in": "body",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "userID": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    }
                                }
                            }
                        },
                        "required": true
                    }
                ],
                "tags": [
                    "User"
                ],
                "responses": {
                    "200": {
                        "description": "json格式的token、refreshToken及其有效期",
                        "schema": {
                            "$ref": "#/definitions/BaseResponse-AddUser"
                        }
                    },
                    "403": {
                        "description": "Unexpected error，没有权限，或token不合法"
                    }
                }
            }
        },
        "/{companyKey}/{app_name}/users": {
            "delete": {
                "summary": "批量删除用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "companyKey",
                        "in": "path",
                        "type": "string",
                        "required": true
                    },
                    {
                        "name": "app_name",
                        "in": "path",
                        "type": "string",
                        "required": true
                    },
                    {
                        "name": "userList",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "userID": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "tags": [
                    "User"
                ],
                "responses": {
                    "200": {
                        "description": "successful operation",
                        "schema": {
                            "$ref": "#/definitions/Pet"
                        }
                    },
                    "403": {
                        "description": "Unexpected error，没有权限，或token不合法"
                    }
                }
            }
        },
        "/{company_key}/{app_name}/users/{user_id}/password": {
            "put": {
                "summary": "修改用户密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "company_key",
                        "in": "path",
                        "type": "string",
                        "required": true
                    },
                    {
                        "name": "app_name",
                        "in": "path",
                        "type": "string",
                        "required": true
                    },
                    {
                        "name": "user_id",
                        "in": "path",
                        "type": "string",
                        "required": true
                    }
                ],
                "tags": [
                    "User"
                ],
                "responses": {
                    "200": {
                        "description": "successful operation",
                        "schema": {
                            "$ref": "#/definitions/BaseResponse"
                        }
                    },
                    "403": {
                        "description": "Unexpected error，没有权限，或token不合法"
                    }
                }
            }
        },
        "/{company_key}/{app_name}/users/{user_id}/deactivate": {
            "post": {
                "summary": "账号禁用",
                "description": "帐号禁用后系统会发协议消息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "company_key",
                        "in": "path",
                        "type": "string",
                        "required": true
                    },
                    {
                        "name": "app_name",
                        "in": "path",
                        "type": "string",
                        "required": true
                    },
                    {
                        "name": "user_id",
                        "in": "path",
                        "type": "string",
                        "required": true
                    }
                ],
                "tags": [
                    "User"
                ],
                "responses": {
                    "200": {
                        "description": "successful operation",
                        "schema": {
                            "$ref": "#/definitions/BaseResponse"
                        }
                    },
                    "403": {
                        "description": "Unexpected error，没有权限，或token不合法"
                    }
                }
            }
        },
        "/{company_key}/{app_name}/users/{user_id}/activate": {
            "post": {
                "summary": "账号解禁",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "company_key",
                        "in": "path",
                        "type": "string",
                        "required": true
                    },
                    {
                        "name": "app_name",
                        "in": "path",
                        "type": "string",
                        "required": true
                    },
                    {
                        "name": "user_id",
                        "in": "path",
                        "type": "string",
                        "required": true
                    }
                ],
                "tags": [
                    "User"
                ],
                "responses": {
                    "200": {
                        "description": "successful operation",
                        "schema": {
                            "$ref": "#/definitions/BaseResponse"
                        }
                    },
                    "403": {
                        "description": "Unexpected error，没有权限，或token不合法"
                    }
                }
            }
        },
        "/{company_key}/{app_name}/users/{user_id}": {
            "get": {
                "summary": "获取帐号信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "company_key",
                        "in": "path",
                        "type": "string",
                        "required": true
                    },
                    {
                        "name": "app_name",
                        "in": "path",
                        "type": "string",
                        "required": true
                    },
                    {
                        "name": "user_id",
                        "in": "path",
                        "type": "string",
                        "required": true
                    }
                ],
                "tags": [
                    "User"
                ],
                "responses": {
                    "200": {
                        "description": "successful operation",
                        "schema": {
                            "$ref": "#/definitions/BaseResponse-UserDto"
                        }
                    },
                    "403": {
                        "description": "Unexpected error，没有权限，或token不合法"
                    }
                }
            }
        }
    },
    "definitions": {
        "BaseResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "boolean"
                },
                "code": {
                    "type": "integer",
                    "format": "int",
                    "description": "错误码"
                },
                "msg": {
                    "type": "string",
                    "description": "错误信息"
                },
                "data": {}
            }
        },
        "BaseResponse-Token": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "boolean"
                },
                "code": {
                    "type": "integer",
                    "format": "int",
                    "description": "错误码"
                },
                "msg": {
                    "type": "string",
                    "description": "错误信息"
                },
                "data": {
                    "$ref": "#/definitions/Token"
                }
            }
        },
        "BaseResponse-AddUser": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "boolean"
                },
                "code": {
                    "type": "integer",
                    "format": "int",
                    "description": "错误码"
                },
                "msg": {
                    "type": "string",
                    "description": "错误信息"
                },
                "data": {
                    "type": "object",
                    "properties": {
                        "dup": {
                            "items": {
                                "type": "string"
                            }
                        },
                        "err": {
                            "items": {
                                "type": "string"
                            }
                        },
                        "new": {
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "BaseResponse-UserDto": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "boolean"
                },
                "code": {
                    "type": "integer",
                    "format": "int",
                    "description": "错误码"
                },
                "msg": {
                    "type": "string",
                    "description": "错误信息"
                },
                "data": {
                    "$ref": "#/definitions/UserDto"
                }
            }
        },
        "BaseResponse-ChatGroupDto": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "boolean"
                },
                "code": {
                    "type": "integer",
                    "format": "int",
                    "description": "错误码"
                },
                "msg": {
                    "type": "string",
                    "description": "错误信息"
                },
                "data": {
                    "$ref": "#/definitions/ChatGroupDto"
                }
            }
        },
        "BaseResponse-ChatRoomDto": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "boolean"
                },
                "code": {
                    "type": "integer",
                    "format": "int",
                    "description": "错误码"
                },
                "msg": {
                    "type": "string",
                    "description": "错误信息"
                },
                "data": {
                    "$ref": "#/definitions/ChatRoomDto"
                }
            }
        },
        "Token": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "refreshToken": {
                    "type": "string"
                },
                "tokenExpires": {
                    "type": "number",
                    "format": "long"
                },
                "refreshExpires": {
                    "type": "number",
                    "format": "long"
                }
            }
        },
        "UserDto": {
            "type": "object",
            "properties": {
                "userID": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "activated": {
                    "type": "boolean"
                }
            }
        },
        "ChatGroupDto": {
            "type": "object",
            "properties": {
                "groupID": {
                    "type": "string"
                },
                "ownerID": {
                    "type": "string"
                },
                "newOwnerName": {
                    "type": "object",
                    "format": "Date"
                },
                "membersOnly": {
                    "type": "object",
                    "format": "Date"
                },
                "allowInvites": {
                    "type": "object",
                    "format": "Date"
                },
                "maxUserNum": {
                    "type": "boolean"
                },
                "memberSet": {
                    "items": {
                        "type": "string",
                        "description": "memberID"
                    }
                }
            }
        },
        "ChatRoomDto": {
            "type": "object",
            "properties": {
                "roomID": {
                    "type": "string"
                },
                "ownerID": {
                    "type": "string"
                },
                "maxUserNum": {
                    "type": "object",
                    "format": "Date"
                },
                "memberSet": {
                    "items": {
                        "type": "string",
                        "description": "memberID"
                    }
                }
            }
        },
        "Pet": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "format": "int64"
                },
                "status": {
                    "type": "string",
                    "description": "pet status in the store"
                }
            }
        },
        "Error": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "boolean"
                },
                "code": {
                    "type": "number",
                    "format": "int"
                },
                "msg": {
                    "type": "string"
                },
                "data": {}
            }
        }
    }
}
```
* Version: 
* Browser/OS: 

**Issue**
