### ISSUE TITLE
Red required star do not display on arrays

### ISSUE THREAD

**Issue by aleksei-saharov** [swagger-api/swagger-editor#1124]
Hi, all

I have some problems with required properties on [http://editor.swagger.io/](http://editor.swagger.io/)

If I try set array as required property, I can't see **red star** near it.

YAML:
```
Entity:
    type: object
    required:
      - Values
    properties:
      Values:
        description: Array of values.
        type: array
        items:
          type: number
          format: double
```
UI result:
![image](https://cloud.githubusercontent.com/assets/9149712/20639198/e4d7c9f6-b3cd-11e6-807f-d5e25c1d7ab1.png)

Alternative view:
![image](https://cloud.githubusercontent.com/assets/9149712/20639213/160b9b2e-b3ce-11e6-989f-4dbcf43b60fe.png)

As you can see, everything is good with alternative view, but main view without **red star**.

I can write `minItems: 1` but I will be displayed only if I **expand** property definition using black triangle.
Here I just tell about **outside** information as for simple property.
