### ISSUE TITLE
"Try this operation" doesn't update when editor changes

### ISSUE THREAD

**Issue by OmgImAlexis** [swagger-api/swagger-editor#1142]
I changed my security definition from this.
```
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
```
To this.
```
securityDefinitions:
  x-api-key:
    type: apiKey
    name: x-api-key
    in: header
```

The "Try this operation" section that I already had open  didn't change even after I used the "
Change Authentication" button at the top of the preview section. I was expecting as the rest of the preview panel changes that the security section should too.
