### ISSUE TITLE
A valid JSON schema is not valid in Swagger editor

### ISSUE THREAD

**Issue by gsi-delmo** [swagger-api/swagger-editor#1143]
**Swagger File**

```yaml
 {
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "Just a simple example"
  },
  "paths": {
    "/users": {
      "get": {
        "responses": {
          "200": {
            "description": "Return the list of users",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/user"
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "user": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int32",
          "readOnly": true
        },
        "name": {
          "type": "string"
        },
        "email": {
          "type": "string",
          "format": "email"
        },
        "timezone": {
          "description": "Formatted as an IANA Time Zone Database name, e.g. Europe/London",
          "type": "string"
        }
      }
    },
    "newUser": {
      "allOf": [
        {
          "$ref": "#/definitions/user"
        },
        {
          "type": "object",
          "required": ["name", "email"]
        }
      ]
    }
  }
}
```

* Version: 2.0
* Browser/OS: Chrome 54/Ubuntu 14.04

**Issue**
I pasted the code above in Swagger online editor but it told me:
_code: "OBJECT_MISSING_REQUIRED_PROPERTY_DEFINITION"
message: "Missing required property definition: name"_

However the *definitions* section is perfectly valid according to several JSON Schema online validators:

- http://www.jsonschemavalidator.net/
- http://jsonschemalint.com/#/version/draft-05/markup/json
- https://json-schema-validator.herokuapp.com/

So why newUser definition is not valid in Swagger editor? Ok it's a bit rare to have an object with no properties and a list of required ones but as I said it's valid in JSON Schema.
