### ISSUE TITLE
Invalid warning about not using a definition

### ISSUE THREAD

**Issue by grosch** [swagger-api/swagger-editor#1163]
**Swagger File**

```yaml
definitions:
  TodoBase:
    type: object
    properties: &TODO-BASE-PROPERTIES
      ... list of properties here ...
  TodoPost: 
    type: object
    properties:
      <<: *TODO-BASE-PROPERTIES
      ... list of other properties here
    required:
      ... required attributes ...
  TodoPatch:
    type: object
    properties:
      <<: *TODO-BASE-PROPERTIES
      ... list of other properties here ...
    minProperties: 1
```

* Version: Whatever is current on editor.swagger.io
* Browser/OS: Chrome on Mac

**Issue**

With the above YAML, the editor is giving a big warning that `#/definitions/TodoBase` is not being used.  I'm never going to directly reference it up in the `paths` section but as you can see it's used in the other two definitions via inheritance.

Would be nice to have the editor recognize this and not provide the warning.

**Comment by hkosova** [comment]
To avoid the warning you can put your unused definitions in an arbitrary section prefixed with `x-`, e.g. `x-definitions`. `x-` keys are free-form [vendor extensions](https://github.com/OAI/OpenAPI-Specification/blob/master/guidelines/EXTENSIONS.md) and they are not included in unused definition detection.

```
x-definitions:
  TodoBase:
    type: object
    properties: &TODO-BASE-PROPERTIES
      ... list of properties here ...

definitions:
  ...
```
