### ISSUE TITLE
Multipart form data with boundary

### ISSUE THREAD

**Issue by Karayel** [swagger-api/swagger-editor#1186]
Hı,

I have some problem multipart form data with boundary.

Here is my expected body :

http://imgur.com/a/LTInb

Here is body that is coming from swagger editor:

http://imgur.com/a/W46oF

And my parameters for related api

```
parameters:
        - name: from
          in: formData
          description: "From Number with 90xxxxxxxxxx"
          required: true
          type: string
        - name: to
          in: formData
          description: "To Number with 90xxxxxxxxxx"
          required: true
          type: string
        - name: subject
          in: formData
          description: "Subject"
          required: false
          type: string
        - name: text
          in: formData
          description: "Text"
          required: false
          type: string
        - name: attachment
          in: formData
          description: "Atttachment"
          required: false
          type: file
```

How can I send multipart form data with boundary ?

Thanks
