### ISSUE TITLE
0 is being rejected as integer in try this operation form

### ISSUE THREAD

**Issue by meeech** [swagger-api/swagger-editor#1200]
**Swagger File**

```yaml
 parameters:
        - name: id
          in: query
          required: true
          type: integer
          format: int32
```

* Version:  2.10.5
* Browser/OS:  Chrome

**Issue**
Have a  required parameter declared an an type: integer, format: int32

If I use 0 as the value, Send Request is not clickable. When I change the value to a non-falsy value (like 1) then I can click send request
