### ISSUE TITLE
Localhost hosted swagger-editor not handling multiple file correctly

### ISSUE THREAD

**Issue by JFCote** [swagger-api/swagger-editor#1204]
**Issue**

I have a swagger.yaml file that reference another yaml file (containing the definitions). I've read that it is supposed to be supported, especially if the server for the editor is self hosted (localhost).

When the editor open, I make sure to chose "File/Import File" so I guess the editor should take note of the "root" folder and be able to access to the other files in that folder.

If I look in the F12 console of Chrome, I see this error:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/definitions.yaml
```

And the editor show this error and a couple of others:

```
A deterministic version of a JSON Schema object.
Jump to line 38
Details
 Object
code:  "INVALID_TYPE"
 params: Array [2]
message:  "Expected type object but found type string"
 path: Array [2]
schemaId:  "http://swagger.io/v2/schema.json#"
description:  "A deterministic version of a JSON Schema object."
level: 900
type:  "Swagger Error"
lineNumber: 38
```

* Version: 2.10.3
* Browser/OS:  Chrome 56.0.2924.87 in Windows 10

Here is my setup in the file system:

- swagger-editor (directory containing the code of the editor)
- startEditor.bat (file that start the editor and open in chrome, see content below)
- swagger.yaml (main file)
- definitions.yaml (definition file, referenced by swagger.yaml)

**startEditor.bat**
```
call npm install -g http-server
start chrome "http://localhost:8080"
http-server swagger-editor
```
**swagger.yaml**

```yaml
swagger: '2.0'

info:
  version: "0.0.1"
  title: Testing
  description: Testing
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /test/foo:
    post:
      tags:
        - Foo
      summary: Foo
      description: ""
      operationId: doFoo
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/Something"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/ResponseMeta"
definitions:
  $ref: ./definitions.yaml
```

definitions.yaml
```yaml
ResponseMeta:
  type: object
  required:
    - code
  properties:
    code:
      type: string
    details:
      type: string
    exception:
      type: string
Something:
  type: object
  required:
    - name
  properties:
    name:
      type: string
```
