### ISSUE TITLE
Missing validation error for arrays

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-editor#1239]
If `type: array` is used, we need to verify `items` is provided with it, and if not, throw an error to the user. This applies to all places `type: array` is applicable including model properties and parameter definitions.

An example of a bad definition:
```yaml
      - name: "ids"
        in: "path"
        description: "List of IDs to return"
        required: true
        type: "array"
        collectionFormat: "csv"
```
