### ISSUE TITLE
[Validation] Editor should throw errors on non-existing scopes

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-editor#1259]
Consider the following definition:

```yaml
securityDefinitions:
  api_key:
    type: apiKey
    name: apikey
    in: query

...

      security:
      - api_key:
        - write:appointments
        - read:appointments        
```

When referencing `api_key`, it has no scopes defined in it (regardless of the type). The Editor should throw errors that the scopes being references are not defined.
