### ISSUE TITLE
Security definition that previously worked is invalid in new editor

### ISSUE THREAD

**Issue by gipeshka** [swagger-api/swagger-editor#1299]
Editor complains now about:
```
oauth2_password:
    type: oauth2
    flow: password
    tokenUrl: /oauth2/token
    scopes:
      API_CUSTOMER: Customer authorized
```
Error:
```
Schema error at securityDefinitions.oauth2_password
is not exactly one from <#/definitions/basicAuthenticationSecurity>,<#/definitions/apiKeySecurity>,<#/definitions/oauth2ImplicitSecurity>,<#/definitions/oauth2PasswordSecurity>,<#/definitions/oauth2ApplicationSecurity>,<#/definitions/oauth2AccessCodeSecurity>
```
Tested on http://editor.swagger.io/#!/

Is there anything wrong with the definition?
