### ISSUE TITLE
Swagger editor validation rejects valid type arrays in schema/definition blocks.

### ISSUE THREAD

**Issue by lewchuk** [swagger-api/swagger-editor#1344]
Swagger/OpenAPI version 2 supports type arrays, e.g. `"type": ["number", "null"]` for type declarations in schema blocks such as `#/definitions/XYZ` (https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v2.0/schema.json#L1016). However, swagger editor's additional validation always rejects these (https://github.com/swagger-api/swagger-editor/blob/master/src/plugins/validation/semantic-validators/validators/walker.js#L22).

The following definition should be valid but is rejected:

```yaml
definitions:
  AModel:
    type: object
    description: A model with a nullable field.
    properties:
      title:
        type: [string, 'null']
        description: A field called title that can be null.
```

There is no history on this file so it is unclear to if the second clause in the if statement of the if clause was supposed to account for this.
