### ISSUE TITLE
Mutiple Path Parameters in Path 

### ISSUE THREAD

**Issue by limesinferior** [swagger-api/swagger-editor#1372]
Hello,

My current Problem is: i need to be able to perform the following call: 
`https://{Net-IP}:{Net-Port}/rest/devices/{deviceName}.{deviceID}`

First of all defining a host variable such as:
`host:
   '{Net-IP}:{Net-Port}` is not possible.

Second, if i then try to implement the Path-Parameter in the paths such as:
```
/devices/{deviceName}.{deviceID}/measurePoints:
    get:
      summary: Method returns list of measure points
      parameters:
        - name: deviceName
          in: path
          type: string
          required: true
          description: device Name
        - name: deviceID
          in: path
          type: string
          required: true
          description: device ID
```

then it says Path templating is not allowed. 

I need this type of calls to be translated for Postman, i appreciate your help!
