### ISSUE TITLE
Bug in the "Semantic error" alert

### ISSUE THREAD

**Issue by ppKrauss** [swagger-api/swagger-editor#1381]
Using https://app.swaggerhub.com

The declarations say that `A` and `B` are distinct var-names with distinct datatypes... But editor's validation (so official validation?) triggs the *"Semantic error: Equivalent paths are not allowed"*.

```
  /{A}/xxx:
    get:
      tags:
      - etc.
      summary: etc.
      operationId: op1
      description: etc.
      produces:
      - application/json
      parameters:
      - in: path
        name: A
        description: etc. 
        required: true
        type: integer
        format: int32
        minimum: 1
        maximum: 9999999

  /{B}/xxx:
    get:
      tags:
      - etc.
      summary: etc.
      operationId: op2
      description: etc.
      produces:
      - application/json
      parameters:
      - in: path
        name: B
        description: etc. 
        required: true
        type: string
        pattern: ^[a-z]+$
```

See *type* and *pattern* very distinct... How to do [parameter-overloading](https://en.wikipedia.org/wiki/Function_overloading) with Swagger?
