### ISSUE TITLE
multiline description in schema

### ISSUE THREAD

**Issue by SORC3r3r** [swagger-api/swagger-editor#1401]
Hi,

while describing the attributes in my schema objects, sometimes the description is pretty long and it would be nice to split it into multiple lines.

I tried:

```
attribute_one: 
          type: "string"
          minLength: 1
          enum:
            - "red"
            - "blue"
            - "green"
          required: true
          description: |
            "red" stands for red 

            "blue" stands for blue 

            "green" stands for green 
```

I was expecting it to be like this:

"red" stands for red 
"blue" stands for blue
"green" stands for green 

Instead I got this:

"red" stands for red "blue" stands for blue "green" stands for green 

First I tried to use a table, but that didn´t work either.

**Comment by hkosova** [comment]
http://editor.swagger.io renders your example as multiline.

![screen shot 2017-07-14 at 21 50 48](https://user-images.githubusercontent.com/8576823/28226394-abb7b20a-68de-11e7-9c4b-d8db2bad2a21.png)

Could you clarify where you are seeing the issue?

P.S. `required: true` is not valid in schema properties, you should use the `required` array on the schema level instead:

```
MySchema:
  type: object
  required:
    - attribute_one
```
