### ISSUE TITLE
The "description:" field within a definition doesn't support GFM formatting

### ISSUE THREAD

**Issue by halmai** [swagger-api/swagger-editor#1426]
I wrote the following in the swagger.yaml file:

```
definitions:
    OK-response:
        type: object
        properties:
            result: 
                type: string
                enum: [OK]
                example: "OK"
        description: "
            {

                \"result\": \"OK\"

            }"
                
```

I expected that the JSON in the description appears in a nicely formatted indented JSON. Unfortunately, the indentation does not work, it is just as deep as the { and } symbols.
