### ISSUE TITLE
object-level example would be nice to have

### ISSUE THREAD

**Issue by halmai** [swagger-api/swagger-editor#1427]
Now if I define something in the `definitions:` part like this:

```
definitions:
    OK-response:
        type: object
        properties:
            result: 
                type: string
                enum: [OK]
                example: "OK"
```

then I can define the examples only field-by-field. Besides of this, it would be better to have an `example:` at the object level like this:

```
definitions:
    OK-response:
        type: object
        properties:
            result: 
                type: string
                enum: [OK]
        example: "
            {
                "result": "OK"
            }
        "
```

**Comment by hkosova** [comment]
Examples can be set on the schema level too. Your 2nd example is close, just use the YAML 
`property: value` syntax:
```
definitions:
    OK-response:
        type: object
        properties:
            result: 
                type: string
                enum: [OK]
        example:
          result: OK
```
https://swagger.io/docs/specification/adding-examples/
