### ISSUE TITLE
defining exact response is cumbersome

### ISSUE THREAD

**Issue by halmai** [swagger-api/swagger-editor#1428]
There are some cases when the response JSON structure returned by an API endpoint is always the same. I mean, I would like to specify in the API specification that the result is
```
    {
        "result": "ERROR",
        "error_msg": "ERROR__NO_PERMISSION"
    }
```

The best way I found to describe this, is a 1-element enum for each field. It is quite verbose so it would be nice to have a `value` member describing exact values like this:
```
definitions:
    OK-response:
        type: object
        properties:
            result: 
                type: string
                value: "ERROR"
            error_msg:
                type: string
                value: "ERROR__NO_PERMISSION"
```

It would be even better to define constant responses with complete JSON description, similarly to this one:
```
definitions:
    OK-response:
        object_json: """
            {
                result: "ERROR",
                error_msg: "ERROR__NO_PERMISSION"
            }
        """
```
