### ISSUE TITLE
validation error for in: "query"

### ISSUE THREAD

**Issue by variable** [swagger-api/swagger-editor#1476]
Given the following:
```
paths:
  /:
    get:
      tags:
        - Business
      summary: "Search business listings"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "what"
          in: "query"
          description: ""
          required: true
```

The editor complains about "query" which should be not in there:

```
should be equal to one of the following allowed values:
allowedValues: body
```
