### ISSUE TITLE
Parameter type array crashes Angular codegen

### ISSUE THREAD

**Issue by jobam** [swagger-api/swagger-editor#1578]
Hi,

for a method using an array of string as a parameter, the typescript / Angular 2 codegen crashes.

The method crashes the codegen:

```yaml '/api/Clients/UpdateClientStakeholderList/{clientId}':
    post:
      tags:
        - Clients
      summary: Update the stakeholders linked to a client
      operationId: ApiClientsUpdateClientStakeholderListByClientIdPost
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces: []
      parameters:
        - name: clientId
          in: path
          description: ''
          required: true
          type: integer
          format: int32
        - name: 'stakeholders'
          in: body
          description: ''
          required: false
          schema:
            type: array
            items:
              type: string
```

Editor Version 2.10.3
