### ISSUE TITLE
Swagger Editor does not resolve local files referenced with $ref

### ISSUE THREAD

**Issue by vnalla** [swagger-api/swagger-editor#1630]
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Looks like a bug
| Which Swagger/OpenAPI version?      | Swagger version 2.0
| Which Swagger-Editor version?       | 3.2.2
| How did you install Swagger-Editor? | downloaded from github, unzipped and opened index.html file in FireFox browser
| Which broswer & version?            | FireFox 52.4.0(32-bit52ESRv2
| Which operating system?             | Windows 7

```yaml
   parameters:
        - $ref: './header_parameters.yaml#/xcsimessageid'
        - $ref: './header_parameters.yaml#/xcsitimetolive'
        - $ref: './header_parameters.yaml#/ctnid'
```

```yaml
  parameters:
        - $ref: >-
            file:///C:/OpenAPI/header_parameters.yaml#/xcsimessageid
        - $ref: >-
            file:///C:/OpenAPI/header_parameters.yaml#/xcsitimetolive
        - $ref: 'file:///C:/OpenAPI/header_parameters.yaml#/ctnid'
```
### Configuration (browser query string, constructor, config.yaml)
No special configuration

### Expected Behavior
If the spec is broken in to multiple files, there should be a way to resolve the files with relative path. All the files are in the same directory.

### Current Behavior
ERROR: Could not resolve reference because of: Tried to resolve a relative URL ...
the second one with file:/// prefix results in the error: Could not resolve reference because of: NetworkError when attempting to fetch resource.
Replaced them with http url's but still the same network error as file uri. The files are served from Tomcat 7 and CORS filter enabled at the server level in <CATALINA_BASE>/conf/web.xml file

### Possible Solution
relative path should work

### Context
Trying to break specification in to multiple files.

**Comment by hkosova** [comment]
Related (or duplicate): https://github.com/swagger-api/swagger-editor/issues/1409

**Comment by shockey** [comment]
@vnalla, hopefully you can clarify one thing for me: are you accessing your Swagger-Editor through a `file://` URI or is your Tomcat server serving it to you?

**Comment by vnalla** [comment]
I tied both, with the same error:

```yaml
- $ref: >-
            http://localhost:7070/files/header_parameters.yaml#/xcsimessageid
        - $ref: >-
            http://localhost:7070/files/header_parameters.yaml#/xcsitimetolive
        - $ref: >-
            http://localhost:7070/files/header_parameters.yaml#/ctnid
```
 Could not resolve reference because of: NetworkError when attempting to fetch resource.
