### ISSUE TITLE
"Type" keyword has not been correctly parsed by editor if used as a property attribute in a definition in the field "additionalProperties"

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-editor#1662]
_From @matterove on February 5, 2018 13:15_

This should be a problem only in the editor validation because the client is correctly generated

In attachement you can find an example of the issue
[TypeBugExample1.txt](https://github.com/swagger-api/swagger.io/files/1695202/TypeBugExample1.txt)

_Copied from original issue: swagger-api/swagger.io#210_

**Comment by webron** [comment]
@shockey this should have been resolved with #1343?

**Comment by jennaprice** [comment]
I thought I was having the same problem but it is actually working for me. I have type as property attribute in the Components section.

**Comment by matterove** [comment]
Thank you but we already saw this response but this does not look like it has been solved

If you could please check the example in attachment you can tell if it's our mistake or there is still the issue

**Comment by jennaprice** [comment]
@matterove I did it in yaml, if you need json then convert.
[example.txt](https://github.com/swagger-api/swagger-editor/files/1696198/example.txt)

**Comment by matterove** [comment]
Maybe i did not explain good enough the issue

Your example is correct but my example reports a different problem and we still have it

If you need more information we'll try to properly respond you

**Comment by jennaprice** [comment]
I was able to get `type:` to work as a property name in both 2.0 and 3.0. There were a few syntax errors in the example you gave. Could you say which lines you were having trouble with? Maybe send of a screen shot of the code with and without the the section with the problem.

**Comment by matterove** [comment]
![screenshot](https://user-images.githubusercontent.com/7910300/35865722-91406fe2-0b55-11e8-998a-1e48f5317014.png)

**Comment by jemerald** [comment]
Problem seems to be caused by the `isSubSchema` function in [schema selectors](https://github.com/swagger-api/swagger-editor/blob/master/src/plugins/validate-semantic/selectors.js#L18) incorrectly picking up the `type` node as a sub-schema because it is two levels down from `additionalProperties`.

```
definitions: 
  Pet:
    type: object
    additionalProperties:
      type: object
      properties: 
        type: # this node got selected as sub-schema incorrectly because its grand-parent node is "additionalProperties"
          description: "here there is the bug!!"
          type: string
```
