### ISSUE TITLE
Semantic error at ... Schema "type" key must be a string

### ISSUE THREAD

**Issue by ralfhandl** [swagger-api/swagger-editor#1783]
With Swagger Editor 3.5 when opening a Swagger 2.0 description containing constructs such as

```yaml
    type: object
    properties:
      KeyDate:
        type:
          - string
          - 'null'
```  
I get the error message above.

Opening the same file with Swagger Editor 2.10.5 works fine, as does opening it with Swagger UI 2.x and the latest Swagger UI 3.x.

This seems to be a regression.

Is it planned to be fixed?
