### ISSUE TITLE
Can't $ref parameters

### ISSUE THREAD

**Issue by DavidBiesack** [swagger-api/swagger-editor#182]
Say an API (in Swagger 2.0) has

``` yaml
paths:
  /products
  /products/{productId}
  /products/{productId}/design
  /products/{productId}/marketing
```

I can define productId once in Parameters Definitions Object but it appears I cannot $ref it as per Reference Object of the spec:

``` yaml
  /products/{productId}:
    parameters:
            - { $ref: productId }
parameters:
  productId: 
       name: productId
       in: path
       type: string
       required: true
```

gives me an error,
Missing required property: name at
paths ▹ /products/{productId} ▹ parameters ▹ 0
(I get the same if I omit the braces around the $ref)

Instead, it seems I must explicitly code it:

```
  /products/{productId}
        parameters:
           -  name: productId
              in: path
              type: string
              required: true
        get: ....
  /products/{productId}/design
        parameters:
           -  name: productId
              in: path
              type: string
              required: true
        get: ....
  /products/{productId}/marketing
        parameters:
           -  name: productId
              in: path
              type: string
              required: true
        get: ....
  /products/{productId}/engineering
        parameters:
           -  name: productId
              in: path
              type: string
              required: true
        get: ....
```

(Otherwise the Swagger Editor/UI does not show the parameter for the get method)

See [this google groups discussion](https://groups.google.com/forum/#!topic/swagger-swaggersocket/9hNRPmP8jBw)

**Comment by davisford** [comment]
Hi, I'm having the same exact issue.  The shorthand `- $ref: '#/parameters/someParam'` is giving me errors on editor.swagger.io -- has anyone else found a workaround aside from inlining every parameter, which is awfully repetitive for each op.

**Comment by webron** [comment]
@davisford - copying the snippet @krallin provided above into the editor works just fine.

**Comment by davisford** [comment]
Ok, indeed it does.  I'm a bit baffled on what I'm doing wrong here?

I thought that a path would take a `parameters` object, but it doesn't like whatever I'm feeding it ?

![screen shot 2015-09-08 at 12 48 47 pm](https://cloud.githubusercontent.com/assets/186677/9741370/2a448768-5628-11e5-82c1-5e92164e7177.png)

Under swagger object, `parameters` has:

```yaml
parameters:
    orgId:
       name: orgId
       description: the id of an `org`
       in: path
       type: number
       format: int
    cardId:
       name: cardId
       description: the id of a `giftcard`
       in: path
       type: number
       format: int
```
