### ISSUE TITLE
Semantic error under security requirements

### ISSUE THREAD

**Issue by vksvicky** [swagger-api/swagger-editor#1826]
I have the following API request and need it to be OAuth authenticated and getting an error on the editor (I am using API 2.0 standards)

```
paths:
  /registerUser:
    post:
      security:
        - OAuth2: [write]
      consumes:
        - application/json
      produces:
        - application/json
```

> **Semantic error at paths./registerUser.post.security.0**
> **Security requirements must match a security definition**

I thought this issue was resolved back in December last year, or am I doing something wrong?

Update

```
securityDefinitions:
    OAuth2:
      type: oauth2
      flow: accessCode
      authorizationUrl: https://example.com/oauth/authorize
      tokenUrl: https://example.com/oauth/token
      scopes:
        read: Grants read access
        write: Grants write access
        admin: Grants read and write access to administrative information
```
