### ISSUE TITLE
Examples throwing errors when used within components section

### ISSUE THREAD

**Issue by mindstretch23** [swagger-api/swagger-editor#1911]
The [Adding examples](https://swagger.io/docs/specification/adding-examples/) section of the documentation states `examples` keyword is supported within properties of the components section. I know the interactive documentation is not supported for `examples` keyword as stated [here](https://app.swaggerhub.com/help/openapi-3-support), but the Swagger editor is throwing the errors shown in screenshot below for the example below.

![examples-error](https://user-images.githubusercontent.com/4995491/48983086-b1eb6980-f0a7-11e8-9dcb-a0cc6c47807e.png)

What am I doing wrong here?

Example Swagger/OpenAPI definition:
```
components:
  schemas:
    Inventory:
      type: object
      properties:
        name:
          type: string
          description: The name of the item.
          examples: 
            exampleOne: 
              value: Superman ice cream
            exampleTwo:
              value: Mint ice cream
```

### Describe the bug you're encountering
Swagger editor throwing the attached error

### Steps to reproduce the behavior:
Paste example above into editor

### Expected behavior
No errors in editor
