### ISSUE TITLE
how to claim composition of types?

### ISSUE THREAD

**Issue by skygragon** [swagger-api/swagger-editor#1914]
let's say I have a general error definition like following:
```yaml
ErrorMsg:
  type: "object"
  properties:
    code:
      type: "integer"
    message:
      type: "string"
    data:
       type: ??
```
here the `data` property could be other definitions in vary, how could I reuse this error type in swagger ?
