### ISSUE TITLE
parameter reference on same document of which references an external do not work

### ISSUE THREAD

**Issue by mariotoffia** [swagger-api/swagger-editor#1976]
### Q&A (please complete the following information)
 - OS: windows 10
 - Browser: Edge
 - Version: ?
 - Method of installation: dist
 - Swagger-Editor version: 3.6.27
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
I'm reusing path parameter uuid of which is defined in separate file as follows:
```yaml
uuid:
  in: path
  name: uuid
  description: A UUID e.g. device or application UUID.
  schema:
    type: string
    format: uuid
  example: 9707d52a-a4a2-42e4-ba95-bcccf068b323
  required: true
```

I'm including it into the main document using
```yaml
components:
  parameters:
    uuid:
      $ref: 'common/path/uuid.yaml#/uuid'
```

and uses it in the same document on path/operation like this
```yaml
  /d/{uuid}/provision/ssid:
    post:
      tags:
        - provision
      summary: Post keys, SSID, and other data to onboard the device
      operationId: onboard
      parameters:
        - $ref: '#/components/parameters/uuid'
        - $ref: '#/components/parameters/x-xyz-test'
      requestBody:
```

Swagger-Editor configuration options:
```js
SwaggerEditor({
  // nothing
})
```
### Describe the bug you're encountering

The error i get in the swagger editor is:
*Semantic error at paths./d/{uuid}/provision/image
Declared path parameter "uuid" needs to be defined as a path parameter at either the path or operation level
Jump to line 99*

However, the x-xyz-test is done exactly the same but is ```in: header``` instead of ```in: path``` instead (and is not part of a path expression of course). The ```x-xyz-test``` do work properly in the editor.

The weird thing is that it will render the ```uuid``` correctly for the operation but it will complain and cannot generate anything using the generators. It seems that the linter is complaining but the renderer works properly.

### To reproduce...

See above explanation.

### Expected behavior

(I'm just guessing here:)) - It should resolve the components/parameter/uuid: $ref before resolving the operation param: $ref to the components/… ref.

### Additional context or thoughts

Cheers,
 Mario
