### ISSUE TITLE
Generate dotnetcore server contains double quotes for string enums

### ISSUE THREAD

**Issue by etaletovic** [swagger-api/swagger-editor#1977]
### Q&A (please complete the following information)
 - OS: Windows
 - Browser: Chrome
 - Version: [e.g. 22]
 - Method of installation: editor.swagger.io
 - Swagger-Editor version: editor.swagger.io
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
components:
  schemas:
    Item:
      properties:
        itemCode:
          type: string
          enum:
            - A
            - B
            - C
            - D
            - Other
```

Swagger-Editor configuration options:
```js
SwaggerEditor({
  // your config options here
})
```

```
?yourQueryStringConfig
```

### Describe the bug you're encountering

When I use "Generate Server" and choose dotnetcore, generated code cannot build
because enum values are parsed with double quotes and I have to go in the code and replace things like  [EnumMember(Value = ""A"")] with  [EnumMember(Value = "A")]
