### ISSUE TITLE
Request body with multiple object in parameters in JSON format

### ISSUE THREAD

**Issue by vaibhavn** [swagger-api/swagger-editor#1992]
### Q&A (please complete the following information)
 - OS: Windows10
 - Browser: Firefox
 - Version: 66
 - Method of installation: dist assets
 - Swagger-UI version: 3.10
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration

Swagger/OpenAPI definition:
```yaml
 "/user/createWithList": {
      "post": {
        "tags": [
          "user"
        ],
        "summary": "Creates list of users with given input array",
        "description": "",
        "operationId": "createUsersWithListInput",
        "produces": [
          "application/xml",
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "List of user object",
            "required": true,
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/User"
              }
            }
          }
        ],
        "responses": {
          "default": {
            "description": "successful operation"
          }
        }
      }
    },
```

### Screenshots
https://petstore.swagger.io/?_ga=2.210242835.708059440.1555410030-810955978.1555410030#/
![SwaggerQuery](https://user-images.githubusercontent.com/3889855/57511841-cc4c9300-7327-11e9-853f-9b9c18c79a0f.jpg)

### How can we help?
How can I pass multiple objects like in above screenshot User Object, Task Object, Some primitive data types parameters in same request body in the form of JSON. _formData_ paramter type may not be useful in my case as server does not implemented in such way.

I would like to pass request body as follows:
```yaml
"body": {
    "User": {
        "id": 1,
        "username": "123",
        "firstName": "Rohit",
        "lastName": "NN",
        "email": "xyz@gmail.com",
        "password": "mypwd",
        "phone": "98999999",
        "userStatus": 0
   },
   "Task" : {
        "id" : 123,
        "taskStatus" : "Pending"
   },
   "isOwner": false,
    "startImmediately": true,      
    "subject": "",
    "description": "Submit to Tc release..",
.........
  }

**Comment by Doqnach** [comment]
Already spoke to you on IRC, but I question what you are trying to solve here... because from the looks of things you are trying to have Swagger-UI show form-fields for your custom JSON payload? For consumers of your API this won't matter though. It's only a visual documentation thing.

**Comment by vaibhavn** [comment]
I would like to display an example JSON( and Model). Developer should read API documentation and update some values in example JSON to try it out APIs. It would help user/developer to build an application by referring request/response JSON data.

**Comment by Doqnach** [comment]
https://swagger.io/docs/specification/adding-examples/
https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/api-with-examples.yaml

You can actually add examples that make sense to the docs, and swagger-ui will pick them up too.

**Comment by vaibhavn** [comment]
Thanks for comment, I have already gone through mentioned links.
But I do not have sample JSON to show as an example.

**Comment by vaibhavn** [comment]
I am going to use single model object for now, Thanks @Doqnach !
Same solution is suggested in the following link( refer to answer )
https://stackoverflow.com/questions/41681322/while-creating-the-rest-api-documentation-using-swagger-2-0-getting-this-error

Following is an example in context of an example mentioned in the question,  I need check on how to generate this kind of JSON through SpringFox for me : 
```yaml
.......
          "in": "body",
            "name": "body",
            "description": "Request JSON payload",
            "required": false,
            "schema": {
              "type": "object",
              "properties": {
                 "user":  {
                  "$ref": '#/definitions/User'
                 },
                 "task":  {
                  "$ref": '#/definitions/Task'
                 },
                 "subject": {
                   "type": "string"
                 }
            }
          } 
```

Eventually this will give me a single text field with all multiple parameters into single request body.
I have to mention all request parameter's description in common description text.
