### ISSUE TITLE
Generated documentation issue on schemas containing arrays

### ISSUE THREAD

**Issue by hjpbarcelos** [swagger-api/swagger-editor#203]
I'm trying to reuse some collections. It appears to be working fine, the problem is with the documentation generated in swagger editor:

``` yaml
        - name: body
          in: body
          description: The JSON request body
          required: true
          schema:
            $ref: AssigneeCollection
```

And then I have:

``` yaml
  AssigneeCollection:
    type: array
    items:
      $ref: Assignee
```

Functionally it seems to be OK.

In the docs, at the model section, looks good:
![captura de tela de 2014-10-14 15 21 18](https://cloud.githubusercontent.com/assets/913378/4634295/e9d0c4dc-53ce-11e4-94a8-43388ec09970.png)

But at the paths section, it's shown like:

![captura de tela de 2014-10-14 15 20 16](https://cloud.githubusercontent.com/assets/913378/4634274/c6068a8c-53ce-11e4-9f6a-8d1eca71df9d.png)
