### ISSUE TITLE
recursive model definitions cause infinite loop

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-editor#212]
if you have a model with a self reference, the editor goes crazy:

``` yaml
definitions:
  ScoredTopic:
    properties:
      topics:
        type: array
        items:
          $ref: ScoredTopic
```
