### ISSUE TITLE
Security requirements must match a security definition

### ISSUE THREAD

**Issue by mirindaunicorn** [swagger-api/swagger-editor#2215]
# Q&A (please complete the following information)
 - Swagger-Editor version: 3.0.0
 - Swagger/OpenAPI version:  OpenAPI 3.0

### Content & configuration
I use for fixing and checking https://editor.swagger.io/ and in it I have error "Security requirements must match a security definition". Please, fix it or explain to me please why I have this error cause we use it like in documentation.

Example Swagger/OpenAPI definition:
```yaml
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearer: []
```

### To reproduce...
1. Go to 'https://editor.swagger.io/'
2. Add some endpoints and security part like from example
3. See error 'Security requirements must match a security definition'

### Expected behavior
I expected that I haven't error when I add security block

### Screenshots
<img width="1440" alt="Снимок экрана 2020-08-25 в 12 13 25 ПП" src="https://user-images.githubusercontent.com/40340509/91156259-9bcf6a80-e6cc-11ea-81b3-306276e14f31.png">
