### ISSUE TITLE
RestBed code generator

### ISSUE THREAD

**Issue by undici77** [swagger-api/swagger-editor#2265]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: Firefox
 - Version: 83
 - Method of installation: run index.html
 - Swagger-Editor version: 3.14.7
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration
Exporting for Restbed, models has wrong model parameters name.
For example:

This:

```
  Face:
    properties:
      photo:
        description: jpg photo in base64
        type: string
      template:
        description: template data in base64
        type: string
      version:
        description: Version of face recognition library
        type: string
    type: object
```

become:

```
std::string Face::toJsonString()
{
	std::stringstream ss;
	ptree pt;
	pt.put("Photo", m_Photo);
	pt.put("_template", m__template);
	pt.put("Version", m_Version);
	write_json(ss, pt, false);
	return ss.str();
}
```

instead of:

```
std::string Face::toJsonString()
{
	std::stringstream ss;
	ptree pt;
	pt.put("photo", m_Photo);
	pt.put("template", m__template);
	pt.put("version", m_Version);
	write_json(ss, pt, false);
	return ss.str();
}
```
