### ISSUE TITLE
`Undefined` instead of the protocol in the request header

### ISSUE THREAD

**Issue by fhecorrea** [swagger-api/swagger-editor#2302]
### Q&A (please complete the following information)
 - OS: Ubuntu 18.04 LTS
 - Browser: Google Chrome Version 87.0.4280.88 (Official Build) (64-bit) / Mozilla Firefox v84.0 (64 bits)
 - Method of installation: None
 - Swagger-Editor version: [Web version](https://editor.swagger.io/) (sorry, I don't know how I can identify what its version)
 - Swagger/OpenAPI version: Swagger 2.0, OpenAPI 3.0.1

### Content & configuration
The document I used to make the calls to the API is in the Gist. Follow the link:
  - https://gist.github.com/fhecorrea/b283c2f20f1b8f6c7d0ac517df772a46

The part I think is problematic is at the top of the .yaml file:
```yaml
servers:
  - url: "{protocol}://{environment}.flashentregas.com.br/index.php/api-v1"
    description: Servidor de homologação
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
      environment:
        default: api # Servidor de produção
        enum:
          - api # Serv. de produção
          - api.homolog # Serv. de homologação
```
I've tried to use the string with the exact URL, I've tried to omit, hide, put the URL without SSL, nothing will.

### Screenshots

![url](https://user-images.githubusercontent.com/22400468/103055633-90f0ed80-4579-11eb-9fdb-045bd337f121.png)
Called URL.

![authenticated](https://user-images.githubusercontent.com/22400468/103055644-98b09200-4579-11eb-8859-b13ae55debb8.png)
Screenshot showing that the credentials are OK.

![console 1](https://user-images.githubusercontent.com/22400468/103055645-9b12ec00-4579-11eb-83f0-c828a2018fbe.png)
Requests in the Network tab (note the error below to the right). Below I detail better, but in general, the problem has been the first line, where there is the method, the URL and the presentation protocol:
```text
GET /index.php/api-v1/listar-entregas/9 undefined
Host: api.homolog.flashentregas.com.br
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0
Accept: application/json
Accept-Language: pt-BR,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: https://editor.swagger.io/
Authorization: Basic <hash auth> # all is ok here...
Origin: https://editor.swagger.io
DNT: 1
Connection: keep-alive
```

![console 2](https://user-images.githubusercontent.com/22400468/103055649-9cdcaf80-4579-11eb-9531-3877fd5adff5.png)
Browser console errors

### How can we help?
After I converted the file to OpenAPIv3, calls to the API have this `undefined` in place of what would be `HTTP/1.1` or `HTTP/2`. I only opened this issue on account of having exhausted everything I thought it could be. I've tried to make calls to the same paths just by replacing the URLs and sometimes it works, but just put the URL `api` or `api.homolog` and Basic Auth for the problem to happen again.

Making calls via URLs manually or via Postman, they happen normally, which made me think that it would then be a problem with the JS file responsible for making these calls or else a problem that I generated when assembling the .yaml.

What could be causing this problem? I thank you for your attention and help.

(Sorry for any grammatical errors. I wrote through a translator, because my confidence in writing English is very small).
