### ISSUE TITLE
@tim-lai is this really a bug?

### ISSUE THREAD

**Issue by mathis-m** [swagger-api/swagger-editor#2526]
@tim-lai since the schema viewer does not implement it either we should have a look at this too:

![image](https://user-images.githubusercontent.com/11584315/112389202-a1d60a00-8cf4-11eb-9b44-d605f2f04633.png)

we could choose to render the following insead to do it more verbose. With this one can understand why we generate "string" as sample value.
```yaml
      anyOf:
        - type: string
        - type: number
        - type: integer
        - type: boolean
        - type: array
          items: {}
        - type: object
```

If this is unwanted because it will sort of render some different then the spec defines we should at least give some hint on it:
`Can be any value - string, number, boolean, array or object.`

_Originally posted by @mathis-m in https://github.com/swagger-api/swagger-editor/issues/2416#issuecomment-806155237_
