### ISSUE TITLE
Array return type with referenced items not previewing correctly

### ISSUE THREAD

**Issue by ecerami** [swagger-api/swagger-editor#257]
I have noticed that when one specifies an array return type like so:

```
     description: An array of products
      schema:
        type: array
        items:
          $ref: Product
```

that the preview panel does not understand the Product element and says that it is undefined.

To recreate:
1.  Go to:  http://editor.swagger.io/
2.  File:  Open Example
3.  Select default.yaml
4.  Under /products, note that:  
   
   ```
    Object
    type:  "array"
    items: undefined
   ```

(screenshot attached)

![undefined](https://cloud.githubusercontent.com/assets/1009066/5169089/08933152-73d2-11e4-97c0-4691af58d672.jpg)

Thanks for checking this out!
