### ISSUE TITLE
Support for OpenAPI Specification 3.1.0

### ISSUE THREAD

**Issue by gk12277** [swagger-api/swagger-editor#2638]
Hi, some time back [OpenAPI Specification 3.1.0](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md) was released which supports JsonSchema `2020-12` Draft by default.
Would be great if support could be provided for this.

There are some major changes like null in type

```yaml
phoneNumber:
 type: 
  - "null"
  -  number
```
