### ISSUE TITLE
Object Composition fields are empty in Preview

### ISSUE THREAD

**Issue by SirWellington** [swagger-api/swagger-editor#266]
Whenever I define one object that contains another, it shows up as empty in the Models section of the preview.

Given the following YAML:

``` yaml

definitions:

  Location:
    required:
      - latitude
      - longitude

    properties:
      latitude:
        type: number
        format: double
        minimum: 0.0
        maixmum: 90.0
        description: The Latitude Coordinate. Valid measurements are from 0 to +- 90 degrees
      longitude:
        type: number
        format: double
        minimum: 0.0
        maximum: 180.0
        description: The Longitude Coordinate. Valid measurements are from 0 to +- 180 degrees  

  Dimension:
    required: 
      - width
      - height

    properties:
      width:
        type: integer
        format: int32
        description: Image Width

      height:
        type: integer
        format: int32
        description: Image Height


  Image:
    required:
      - id
      - container
      - timePublished
    properties:

      id:
        type: string
        description: The ID of the Image

      container:
        type: string
        description: The Container this image resides in

      dimension:
        type: object
        description: The Size of the Image
        $ref: Dimension

      timePublished:
        type: string
        format: date-time
        description: The Time this image was first uploaded

      timeOfExpiration:
        type: string
        format: date-time
        description: The Time this image will expire and be deleted. Optional.

      orientation:
        type: number
        format: float
        description: The Orientation Angle of the Image.

      sizeInBytes:
        type: integer
        format: int64
        description: The size of the image in bytes

      location:
        type: object
        format: Location
        description: The Location the Image was taken at.
        $ref: Location

```

The Location and Dimension objects show as `{}`. Could I be referencing it incorrectly?
