### ISSUE TITLE
allOf doesn't render in the UI

### ISSUE THREAD

**Issue by skullmaggots** [swagger-api/swagger-editor#272]
Trying to create a model that uses composition with allOf in the editor like so....

````
  Event:
    discriminator: name
    properties:
      name:
        type: string
    required:
      - name
      
  ReferAFriendEvent:
    allOf:
      - $ref: Event
      - properties: 
          accountId:
            type: integer
          campaignname:
            type: string
````

However the UI just displays an empty list for the ReferAFriendEvent.
Not sure whether this is a bug or composition not supported in the editor UI yet.
