### ISSUE TITLE
`URL_OAS3_GENERATOR=null` does not remove it from the Menu

### ISSUE THREAD

**Issue by GAS85** [swagger-api/swagger-editor#2982]
### Q&A (please complete the following information)
 - OS: Ubuntu 20.04
 - Browser: Firfefox
 - Version: 98
 - Method of installation: docker
 - Swagger-Editor version: 4.2.0

### Content & configuration

Docker config:
```yaml
version: "3.6"
services:
  swaggereditor:
    container_name: swagger
    image: swaggerapi/swagger-editor
    hostname: swagger
    restart: unless-stopped
    environment: 
      - URL_SWAGGER2_GENERATOR=null
      - URL_OAS3_GENERATOR=null
      - URL_SWAGGER2_CONVERTER=null
    ports:
      - 9010:8080
```

### Describe the bug you're encountering

Set `URL_*` to `null` to avoid any Generator and Converter in Intranet area. Generater and converter are removed from the menu, but not OAS3 converter, it is still in menu and will send `POST` request on `FQDN/null` (e.g. `https://FQDN/swagger-editor/null`) and show an error by clicking on it:
![grafik](https://user-images.githubusercontent.com/6813635/159675240-de284206-28ac-4e17-9e85-9fd1d96d4f87.png)

### To reproduce...

1. Deploy with docker configuration from above
2. Click on menu Edit --> Convert to OpenAPI 3
3. Confirm Convertion

### Expected behavior
`URL_OAS3_GENERATOR=null` must also remove "Convert to OpenAPI 3" from menu.

### Additional context or thoughts
Related to #1488
