### ISSUE TITLE
POST formData not working

### ISSUE THREAD

**Issue by clickslide** [swagger-api/swagger-editor#299]
I'm trying to send a simple string as a POST parameter in swagger 2.0. However, I cannot seem to get it to work.

````
    post:
      summary: POST simple parameter
      description: Test
      consumes:
        - application/x-www-form-urlencoded
      parameters:
            name: _method
            in: formData
            type: string
            required: true
            description: testing
````

When I view a log of the $_POST details in my PHP server, the array is empty. It should contain the "_method" parameter. What am I missing?

**Comment by mohsen1** [comment]
Confirmed. It's a bug

Also note that `parameters` should be an array

```yaml
    post:
      summary: POST simple parameter
      description: Test
      consumes:
        - application/x-www-form-urlencoded
      parameters:
          - name: _method
            in: formData
            type: string
            required: true
            description: testing
```
