### ISSUE TITLE
[try] if path parameter is invalid javascript identifier it will not generate URL

### ISSUE THREAD

**Issue by mohsen1** [swagger-api/swagger-editor#304]
For example this:

```yaml
paths:
  /users/{user-\id}:
    parameters:
      - name: user-id
```
