### ISSUE TITLE
Complex type as nested object not generating code in Swagger Editor online

### ISSUE THREAD

**Issue by fmcdev** [swagger-api/swagger-editor#3077]
### Q&A (please complete the following information)
 - OS: Win10 Pro
 - Browser: both Chrome and Edge
 - Version: Edge 101.0.1210.53 (but it's the same on older versions)
 - Method of installation: editor online at editor.swagger.io
 - Swagger-Editor version: online
 - Swagger/OpenAPI version: Swagger 2.0

### Describe the bug you're encountering
Since a while, when defining complex type objects nested inside another complex object, generating code in csharp (or any other language) generate code with the nested object as generic Object type instead of a specific class (Swagger 2.0). This way validation of the nested attributes is lost. The only way to have it working is to define the nested object as a flat object itself and then use $ref to it in the parent object (too bad because I expose to users multiple data models that indeed are not useful by theirselves).

### To reproduce...

I do an example to clearify:

```
  Pet:
    type: "object"
    required:
    - "name"
    - "photoUrls"
    properties:
      id:
        type: "integer"
        format: "int64"
      category:
        type: "object"
        properties:
          id:
            type: "integer"
            format: "int64"
          name:
            type: "string"
      name:
        type: "string"
        example: "doggie"
```

this generates the wrong c# code:
(/csharp-client/src/IO.Swagger/Model/Pet.cs)

```
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public long? Id { get; set; }

        /// <summary>
        /// Gets or Sets Category
        /// </summary>
        [DataMember(Name="category", EmitDefaultValue=false)]
        public Object Category { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

```

This one instead (with every complex type explicitly wrapped into a separate data model):

```
  Pet:
    type: "object"
    required:
    - "name"
    - "photoUrls"
    properties:
      id:
        type: "integer"
        format: "int64"
      category:
        $ref: "#/definitions/Category"
      name:
        type: "string"
        example: "doggie"
```

generates good code:

```
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public long? Id { get; set; }

        /// <summary>
        /// Gets or Sets Category
        /// </summary>
        [DataMember(Name="category", EmitDefaultValue=false)]
        public Category Category { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }
```
I've been using swagger editor since year 2018 and at least until 2020, both the definitions generate good&complete code, because also in the 1st case, an "implicit" class for Category has been built by itself.

I've noticed that with an OpenAPI 3.0 definition, complex objects generate good code with "implicit" class automatically generated.

Thanks for your support.
