### ISSUE TITLE
Create nested arrays on the editor is not working

### ISSUE THREAD

**Issue by FlevasGR** [swagger-api/swagger-editor#339]
Hello, im tyring to create a nested array through the swagger editor but it doesn't seem to work.
From the docs i red about the `type: array` and the `items` however im getting an error on the editor.

**The response im trying to document:**

```
{
   status: 200,
   builds: [
       {
            smartID: "idhere",
            name: "yorg",
            description: "powerPC",
            username: "username",
            dateCreated: "0000-00-00"
        }
  ]
}
```

**What im writing on the editor**

```
BuildsByUser:
    properties:
      status:
        type: integer
        description: The HTTP status code
      data: 
        type: array
        description: An array of data
        items:
          smartID:
            type: string
            description: Unique identifier for each build
          name:
            type: integer
            description: The name of the build
          description:
            type: string
            description: The build description
          username:
            type: integer
            description: The user which created the build
          dateCreated:
            type: string
            description: The date the build was created
```
**The error**

```
✖ Swagger Error
Data does not match any schemas from 'anyOf'
Jump to line 373
Details
 Object
```

**Comment by webron** [comment]
That's not a valid definition. I think you're looking for something like this:

```yaml
  BuildsByUser: 
    properties: 
      status: 
        type: "integer"
        description: "The HTTP status code"
      data: 
        type: "array"
        description: "An array of data"
        items: 
          type: "object"
          properties: 
            smartID: 
              type: "string"
              description: "Unique identifier for each build"
            name: 
              type: "integer"
              description: "The name of the build"
            description: 
              type: "string"
              description: "The build description"
            username: 
              type: "integer"
              description: "The user which created the build"
            dateCreated: 
              type: "string"
              description: "The date the build was created"
```
