### ISSUE TITLE
Degradation after v4.0.2 URL to the swagger file not working in v4 `?url=`

### ISSUE THREAD

**Issue by GAS85** [swagger-api/swagger-editor#3510]
### Q&A (please complete the following information)
 - OS: Ubuntu
 - Browser: Firefox
 - Version: 104.2
 - Method of installation: Docker
 - Swagger-Editor version: 4.4.0
 - Swagger/OpenAPI version: Any of them

### Content & configuration

Swagger supports direct OAS open via URL Path in format `https://fqdn/swaggereditor/?url=https://FQDN/myCoolService/swagger.json`. This works fine in v3 e.g. `3.18.2` or till `4.0.2`.
After update to editor `4.0.4`, or `4.4.1` - it does not work anymore, there is no requests to the provided path in Browser>Debugging>Network and "Swagger Petstore - OpenAPI 3.0" will opens.

### Describe the bug you're encountering

- Example Swagger/OpenAPI definition: https://raw.githubusercontent.com/gotify/server/v2.1.7/docs/spec.json
- URL test: https://git.sitnikov.ga/swagger-editor/?url=https://raw.githubusercontent.com/gotify/server/v2.1.7/docs/spec.json
- For v3 you can see request to provided URL:
![](https://cloud.sitnikov.ga/index.php/s/f8TZrQMbbsLJWWH/download?path=%2F&files=v3.png)
- For v4 there is no request to provided URL happens:
![](https://cloud.sitnikov.ga/index.php/s/f8TZrQMbbsLJWWH/download?path=%2F&files=v4.png)

Swagger-Editor configuration options in container:
```yaml
  swaggereditor:
    container_name: swagger
    image: swaggerapi/swagger-editor:latest
    hostname: swagger
    restart: unless-stopped
    environment: 
      - URL_SWAGGER2_GENERATOR=null
      - URL_OAS3_GENERATOR=null
      - URL_SWAGGER2_CONVERTER=null
    ports:
      - 9010:8080
```

### To reproduce...

1. Deploy swagger UI v4.0.4+
2. Open Editor in UI
3. Add `?url=https://raw.githubusercontent.com/gotify/server/v2.1.7/docs/spec.json` to the path
4. that Pet store is opened instead

### Expected behavior

Provided OAS must be opened instead.
