### ISSUE TITLE
Parameters Object not implemented as specification defines

### ISSUE THREAD

**Issue by sarnowski** [swagger-api/swagger-editor#371]
The [Parameters Object specification](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#parametersDefinitionsObject) defines the parameters as an object but the editor only handles it as an array.

Spec example:

```yaml
parameters:
  skipParam:
    name: skip
    in: query
    description: number of items to skip
    required: true
    type: integer
    format: int32
```

Editor example:

```yaml
parameters:
  - 
    name: size
    in: query
    description: Size of array
    required: true
    type: number
    format: double
```
