### ISSUE TITLE
SwaggerEditor@next: allOf/oneOf/anyOf with a $ref subschema are flagged as errors

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-editor#3722]
### Q&A (please complete the following information)
 - OS: macOS 12.6.1
 - Browser: Chrome latest
 - Method of installation: https://editor-next.swagger.io/
 - Swagger-Editor version: 5.0.0-alpha.40
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.0
info:
  title: allOf with one subschema
  version: 0.0.1
paths: {}
components:
  schemas:
    Foo:
      type: object
    Bar:
      allOf:  # or 'oneOf' or 'anyOf'
        - $ref: '#/components/schemas/Foo'
      description: something something
```

### Describe the bug you're encountering

The definition above is valid, but SwaggerEditor@next flags the `Bar` schema:
> allOf must be a non-empty array of schemas

A similar error appears if you replace `allOf` with `oneOf` or `anyOf`.

<br/>

The error appears only for OAS 3.0.x definitions. It does not appear for equivalent OAS 3.1 and 2.0 definitions.

<br/>

It looks like the issue happens if at least one of the subschemas in `allOf`/`oneOf`/`anyOf` is a `$ref`. If the subschemas are inlined, no errors appear.
```yaml
    # no errors
    Bar2:
      allOf:
        - type: object
      description: something something

    # no errors
    Bar3:
      oneOf:
        - type: string
        - type: integer
      description: something something
```

### To reproduce...

1. Go to https://editor-next.swagger.io
2. Replace the default definition with the one provided above.

### Actual behavior
A validation error appears:

Line | Description
----|-------------
10 |  allOf must be a non-empty array of schemas

### Expected behavior
No validation errors.

### Screenshots
<img width="467" alt="Screenshot 2022-12-09 at 14 53 36" src="https://user-images.githubusercontent.com/8576823/206686518-1cbbd11e-be0c-4c32-b1fc-45e0c7c0c516.png">

### Additional context or thoughts
n/a
