### ISSUE TITLE
Duplicate Array created: Error: Value must be a string

### ISSUE THREAD

**Issue by RobertoDonPedro** [swagger-api/swagger-editor#3754]
Hi,

when defining and referencing the following component (in a query parameter)
```
components:
  schemas:
    data:
      type: object
      properties:  
        return_fields: 
          type: array
          items: 
            type: string
            example: 
              - field1
              - field2
              - field3
```
the "Try-it-out" description generates 
```
{
  "return_fields": [
    [
      "field1",
      "field2",
      "field3"
    ]
  ]
}
```
and this validation error occurs

> propKeyreturn_fieldserrorindex0errorValue must be a string

As opposed to the "return_fields" object above the API expects an array without duplicate square brackets like so
```
{
  "return_fields": [
      "field1",
      "field2",
      "field3"
  ]
}
```

How can I achieve this? ( I tried a lot yet but nothing seems to work)
Thanks

### Q&A (please complete the following information)
 - OS: [Windows 10]
 - Browser: [chrome]
 - Method of installation: [Docker]
 - Swagger-Editor version: [v4.6.0]
 - OpenAPI version: [OpenAPI 3.0]
