### ISSUE TITLE
Support JSON comments

### ISSUE THREAD

**Issue by azat-io** [swagger-api/swagger-editor#3792]
Hi there.

I'm using [JSON viewer](https://chrome.google.com/webstore/detail/json-viewer/gbmdgpbipfallnflgajpaliibnhdgobh) Chrome extension. This browser extension adds a comment to the beginning of the JSON file. It would be more convenient to copy if Swagger Editor also supported comments

```json
// 20230129192829
// https://cardspro.capitalist.net/v3/api-docs

{
  "openapi": "3.0.1",
  "info": {
    "title": "OpenAPI definition",
    "version": "v0"
  },
 // ...
}
```

**Comment by char0n** [comment]
Hi @azat-io,

Both https://editor.swagger.io/ and https://editor-next.swagger.io/ support comments in JSON. As JSON is a s subset of YAML 1.2, you can write following JSON with YAML comments:

```yaml
# 20230129192829
# https://cardspro.capitalist.net/v3/api-docs

{
  "openapi": "3.0.1",
  "info": {
    "title": "OpenAPI definition",
    "version": "v0"
  },
 # ...
}
```

The issue with your comments, is that using `//` to designate comment is not part of either JSON or YAML standard, but rather EcmaScript specification. Thus making comment like this in JSON is highly random and non-standard and we will not be adding support for comments like this now and probably in future as well. I'm sorry.
