### ISSUE TITLE
date and dateTime considered as Errors?

### ISSUE THREAD

**Issue by freak4pc** [swagger-api/swagger-editor#405]
This specification: 

```
parameters:
        -
          name: gender
          in: formData
          description: "User's gender"
          required: true
          type: string
          enum: [m, f]
          default: m
        -
          name: birthday
          in: formData
          description: "User's birth date"
          required: true
          type: date
```

Results in this:
![image](https://cloud.githubusercontent.com/assets/605076/7178247/f8ca3f20-e435-11e4-82d5-630e048ae76f.png)

When changing the type from `date` to `string` , the error message disappears.
