### ISSUE TITLE
Argument integer 0 not supported in path

### ISSUE THREAD

**Issue by CaillotKi** [swagger-api/swagger-editor#472]
I use the demo version of swagger with Yaml format and need to pass an integer (named duration) through the path.

``` yaml
/hardware/led/test/{duration}:
put:
  parameters:
    - name: Authorization
      in: header
      description: Authorization token
      required: true
      type: string
    - name: duration
      in: path
      description: Duration the leds will blink (in ms)
      required: true
      type: number
      minimum: 0
      maximum: 200
  tags:
    - Hardware
    - Led
    - WIP
  summary: Make every leds blink
```

Unfortunately swagger does not accept the 0 value. Other value are accepted:

```
PUT http://10.110.0.94:8080/hardware/led/test/1000 HTTP/1.1
```

 but the 0 value is replaced by the name of the parameter:

```
PUT http://localhost:8080/hardware/led/test/{duration} HTTP/1.1
```

I've posted on Stack in case it's a well known problem but it appears it's not.
