### ISSUE TITLE
Client HTML2 doesn't have parameters' defaults 

### ISSUE THREAD

**Issue by ybbih** [swagger-api/swagger-editor#4763]
### Q&A 
 - OS: Ubuntu 22.04
 - Browser: Google Chrome
 - Version: 120.0.6099.224 (x64)
 - Method of installation: Online demo (https://editor.swagger.io/)
 - Swagger-Editor version: latest available on demo
 - Swagger/OpenAPI version: latest available on demo

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
components:
  parameters:
    limitParam:
      in: query
      name: limit
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 500
        default: 100
      description: The numbers of items to return.
```

Swagger-Editor configuration options:
Default from https://editor.swagger.io/

### Describe the bug you're encountering
When generating for client to HTML, default parameter value is shown but when choosing HTML2, default value is not visible.

HTML:
![image](https://github.com/swagger-api/swagger-editor/assets/49154305/ccf711d5-e291-4c31-9d0e-0b7c381890cc)

HTML2:
![image](https://github.com/swagger-api/swagger-editor/assets/49154305/e16b5526-fe61-45ed-ad78-bee2c35d4d9e)

### To reproduce...

1. Go to https://editor.swagger.io/
2. Create any route with queyr parameter and defined default value.
3. Generate html2 for client

### Expected behavior
HTML2 output includes default value next to parameter description.
