### ISSUE TITLE
Support multiple `apiKey` securities in header

### ISSUE THREAD

**Issue by jwhitefield-hark** [swagger-api/swagger-editor#508]
In an attempt to supply multiple security headings to each of my web services I added a definition for each parameter, and added them to the security. I believed I had set this up incorrectly as within the swagger editor ( 2.8.x  bundled with a127 ), I was only able to select a single security header. 

After asking some guys on the Swagger IRC they suggested that this may not be a problem with the definition but the editor, as you should be able to add multiple security headers. I have also tried this on the Live editor ( http://editor.swagger.io/#/ ) which is currently at version 2.9.6. Adding my bellow definition, it only allowed me to add the userEmail header not the client Id.

```yaml
securityDefinitions:
  userEmail:
    type: apiKey
    name: User Email
    in: header
  clientId:
    type: apiKey
    name: Client Id
    in: header

security: [ { userEmail: [], clientId: []  } ]
```
Any support on the issue would be greatly appreciated.
Thanks
Jon
