### ISSUE TITLE
Swagger editor won't put false boolean values in the URL for "try this operation" 

### ISSUE THREAD

**Issue by Syzygy24** [swagger-api/swagger-editor#542]
The segment in question is

``` yaml
parameters:
          name: debug
          in: query
          description: |
            Parameter must be included as part of the URI. If set to true, ERROR
            message will return full entity response message.
            ** keep off if performance is a consideration **
          required: false
          type: boolean
          default: false
          allowEmptyValue: false
```

Our api won't allow requests with an empty debug value. I would just like to be able to pass "false" in, but nothing I tried will allow it. Changing it to true makes it work just fine, but there are performance considerations with that feature. Changing the value to false in the dropdown menu just makes it an empty string rather than false and the response returns an error because we passed in an empty value for debug.

GET http://{url}/v1/stores?debug= HTTP/1.1

Adding "allowEmptyValue: false", changing required to true, and adding "default: false" haven't helped.
Is there a way around this?
