### ISSUE TITLE
Json must be an object with enumerations

### ISSUE THREAD

**Issue by gdscei** [swagger-api/swagger-editor#573]
The editor doesn't seem to like using enumerations when I write it the regular "list" way:

```
nameOfProperty:
        type: string
        enum:
          - enum1
          - enum2
```
I get the error back "json must be an object". However, when I write in the array way:

```
nameOfProperty:
        type: string
        enum: [
          enum1,
          enum2
          ]
```
It's fine and doesn't give an error.

Both methods should work fine, right?
