### ISSUE TITLE
`required` property does not work for boolean values

### ISSUE THREAD

**Issue by davisford** [swagger-api/swagger-editor#580]
If you have a property in a model definition like: 

```yaml
Foo:
  required:
    - disabled
  properties:
    disabled:
      type: boolean
```

And you try to post it in the body of the JSON, the UI will allow you to toggle it to true, and it will send it.  But if you toggle it to false, it deletes the property altogether (assuming because it is falsey).  However, one still needs to be able to send boolean values that are false (e.g. to toggle a switch from on to off)
