### ISSUE TITLE
allowEmptyValue has no effect on "try this operation" (is always true)

### ISSUE THREAD

**Issue by ruslanjur** [swagger-api/swagger-editor#584]
Even when `allowEmptyValue` is explicitly set to *false* **Try this operation** always sends the parameter with an empty value

For example:
```
      parameters:
        - name: param
          in: path
          required: true
          type: string
        - name: callback
          in: query
          description: Callback function
          required: false
          allowEmptyValue: false
          type: string
```

**Try this operation** will send
`GET http://localhost:8080/get/{param}?callback= HTTP/1.1`

[Here](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md) it says that `allowEmptyValue Sets the ability to pass empty-valued parameters. This is valid only for either query or formData parameters and allows you to send a parameter with a name only or an empty value. Default value is false.` which implies that `?callback=` should be sent only in case of `allowEmptyValue: true`
