### ISSUE TITLE
How to create schema with generic JSON input   label:question 

### ISSUE THREAD

**Issue by introvertmac** [swagger-api/swagger-editor#590]
I want to take  JSON input from user inside body , can swagger create schema based of this JSON itself ? JSON can be different  every time depending on user input .

**Comment by mohsen1** [comment]
An empty object `{}` is the most generic JSON Schema You can use that...

**Comment by introvertmac** [comment]
what should be the type in yaml ?
I have used string , where user can dump his JSON

  OrderDetail:
    description: order json provided by vendor
    required:
      - orderJson
    properties:
      orderJson:
        type: string

**Comment by webron** [comment]
No type.

```yaml
  OrderDetail:
    description: order json provided by vendor
    required:
      - orderJson
    properties:
      orderJson: {}
```

Though if you know it's a JSON Object:

```yaml
  OrderDetail:
    description: order json provided by vendor
    required:
      - orderJson
    properties:
      orderJson:
        type: object
```
