### ISSUE TITLE
custom request signing

### ISSUE THREAD

**Issue by davisford** [swagger-api/swagger-editor#593]
Hi, per [swagger api: custom request signing](https://github.com/swagger-api/swagger-js/blob/master/README.md#custom-request-signing)

Is there any way to make this work with the editor?  Specifically, I'm trying to get [JWT](https://tools.ietf.org/html/rfc7519) authentication to work with the editor + my api spec.  Seems it [has been discussed before, and there is a solution with swagger-js](https://github.com/swagger-api/swagger-ui/issues/818), which I'm  assuming is used in the editor?

**Comment by mohsen1** [comment]
No, Swagger Editor is not using Swagger.js. Isn't JWT just a token? I believe Swagger Editor should't care how your generate that token.

**Comment by davisford** [comment]
JWT is a token.  I have an unprotected endpoint to authenticate and get the token, but I'm having trouble specifying the `securityDefinition` and `security` section.  I'm fine with pasting the token in, and I have that working via 

![screen shot 2015-08-18 at 10 33 53 pm](https://cloud.githubusercontent.com/assets/186677/9347564/3eb00e28-45f9-11e5-912c-9b0de4f672f6.png)

..but I'm having trouble specifying how to secure a particular endpoint with the token.   JWT server libs typically expect the format `Authorization: Bearer <token here>`.  I'm not seeing that get posted through after I add the token.

```yaml
securityDefinitions:
  auth:
    type: apiKey
    description: autheticate with jwt
    name: Authorization
    in: header
```

and on an endpoint:

```yaml
    post:
      security:
        - auth: []
```
