### ISSUE TITLE
Editor cannot send request with file

### ISSUE THREAD

**Issue by hantuzun** [swagger-api/swagger-editor#599]
Hi,

We have an endpoint with the following parameters:

```
      parameters:
        - name: upload
          in: formData
          required: true
          type: file
```

I wanted to try the endpoint using the editor. I choose a file on the editor, set the header and then hit the "send request".

However, the editor doesn't send the file content. The following is the body is being send by the editor:

```
(upload: actions.csv)
```

Whereas a proper request should have such a body:

```
(--------------------------a1c5ec12084324b4 
Content-Disposition: form-data; name="upload"; filename="actions.csv" 
Content-Type: application/octet-stream 
 "230", "969",  4 "90",  "1101", 4 "276", "234",  5 "325", "168",  3 "15",  "754",  5 "324", "298",  5 "73",  "48",   2 "232", "315",  5 "328", "98",   4 "128", "588",  5 
 --------------------------a1c5ec12084324b4--)
```

Could you confirm that this issue about the swagger-editor?
