### ISSUE TITLE
Swagger Editor, generate jax-rs server crashes when using "password" format

### ISSUE THREAD

**Issue by gitburr** [swagger-api/swagger-editor#613]
Example below. Uncomment  "#format: password", try to generate jax-rs server, receive error.
```yaml
definitions:
  Test:
    required:
    - name
    properties:
      name:
        type: string
      id:
        type: string
      awsKeyId:
        type: string
      awsSecretKey:
        type: string
        #format: password
      bucket:
        type: string
      dataSize:
        type: integer
        format: int64
      numberItems:
        type: integer
        format: int64
```
