### ISSUE TITLE
Validation of schema should check that 'example' match the schema

### ISSUE THREAD

**Issue by dolmen** [swagger-api/swagger-editor#673]
The validation of a schema (in `/definitions`) should check that if an `example` is provided, the value matches the schema.

Here is for example a mistake I made that should be caught as an error:
```yaml
definitions:
  PhoneNumber:
    description: Phone number of the *User* in international format, for SMS notifications.
    example: +3300000000
    type: string
    pattern: '^\+[0-9]{5,}$'
```
In YAML, +[0-9] is taken as number, not a string. I should have quoted the `example` value.
