### ISSUE TITLE
Please display circle-reference in the Editor when a model causes an infinite-loop. (feature request)

### ISSUE THREAD

**Issue by devbnz** [swagger-api/swagger-editor#704]
Example: 

``` yaml
Definitions:
  ScoredTopic:
    properties:
      topics:
        type: array
        items:
          $ref: ScoredTopic 
```

Taken from: 
https://github.com/swagger-api/swagger-editor/issues/212

When you open that in the Editor, the second nesting will be undefined.

Ie.:
1. Go to the twitter example
2. Scroll down to POST /statuses/retweets/{id} 
3. Go to responses, open up current_user_retweet
4. Go to Tweets and take a look on current_user_retweet
5. nested value will be undefined.

Please rename this undefined message to circle / loop / self-reference.
