### ISSUE TITLE
Misterious $folded: appears

### ISSUE THREAD

**Issue by crystalfp** [swagger-api/swagger-editor#742]
Just started using Swagger editor: fantastic! I'm working on windows using Firefox.
I use the definition section to factorize the same response from two methods this way:

```
definitions:
  Annotation:
    type: object
    properties:
      id:
        type: string
      title:
        type: string
      text:
        type: string
        description: Content of the annotation
```

And in both methods I refer to it using:

```
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/Annotation'
```

Now only for the first method in the preview panel a mysterious field called $folded: appears after 'test'.
Also if I push the two arrows button to switch to json, the field becomes: `$folded: false`
What is it? Seems it appears after I collapsed and expanded my methods in the preview panel.
To make it disappears I have to load one of the examples and then reload my file.
Thanks!
mario
