### ISSUE TITLE
collectionFormat - editor does not build url correctly

### ISSUE THREAD

**Issue by MReinigJr** [swagger-api/swagger-editor#776]
Hello, 

If a query parameter is specified as an ``array`` with a ``collectionFormat`` other than ``multi``, example:
```
get:
    tags:
      - shipping
    description: Calculates the shipping charges for the list of item IDs provided.
    parameters:
      - name: itemIds
        in: query
        description: Item IDs in order.
        required: true
        type: array
        items:
          type: integer
        collectionFormat: csv
```

The url built by the editor uses the ``multi`` format always.  So if I specify ``csv``, the editor builds a query in the ``multi`` format:

```
GET https://apiurl/v1/order/shipping?itemIds[]=1&itemIds[]=2 HTTP/1.1
```
when it should be:
```
GET https://apiurl/v1/order/shipping?itemIds=1%2C2 HTTP/1.1
```

This issue appears to only be applicable to the editor and not the UI.

Thanks for the great api tools,
Michael
