### ISSUE TITLE
Composite security definitions or conditional security

### ISSUE THREAD

**Issue by ben3005** [swagger-api/swagger-editor#821]
Following the swagger 2.0 spec.
Is it possible to define a security for an endpoint that has the set-up:

``` yaml
paths:
  '/endpoint/'
    security:
     - securityDefinitionA AND securityDefinitionB
     - securityDefinitionC

securityDefinitions:
  securityDefinitionA:
    type: apiKey
    name: X-HeaderA
    in: header
  securityDefinitionB:
    type: apiKey
    name: X-HeaderB
    in: header
  securityDefinitionC:
    type: apiKey
    name: X-HeaderC
    in: header
```

essentially the security for the endpoint is:

( securityDefinitionA AND securityDefinitionB )
OR
securityDefinitionC

**Comment by webron** [comment]
Yes. `security` is an array of [Security Requirement Objects](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#securityRequirementObject). Each Security Requirement Object can contain multiple security definitions, and between them there's a logical AND.

**Comment by ben3005** [comment]
Thanks,

I'm having some trouble trying to figure out how to actually write a security requirement object:

Are the declared separately or are the declared inline?

``` yaml
paths:
  '/endpoint/'
    security:
     - CompositeSecurity
       - securityDefinitionA: []
       - securityDefinitionB: []
     - securityDefinitionC: []

securityDefinitions:
  securityDefinitionA:
    type: apiKey
    name: X-HeaderA
    in: header
  securityDefinitionB:
    type: apiKey
    name: X-HeaderB
    in: header
  securityDefinitionC:
    type: apiKey
    name: X-HeaderC
    in: header
```

or

``` yaml
paths:
  '/endpoint/'
    security:
     - CompositeSecurity: []
     - securityDefinitionC: []

securityRequirements:
  CompositeSecurity:
    - securityDefinitionA: []
    - securityDefinitionB: []

securityDefinitions:
  securityDefinitionA:
    type: apiKey
    name: X-HeaderA
    in: header
  securityDefinitionB:
    type: apiKey
    name: X-HeaderB
    in: header
  securityDefinitionC:
    type: apiKey
    name: X-HeaderC
    in: header
```

both of these cause swagger-editor validation errors so i'm doing something wrong.
so the question is:
how and where do i define a Security Requirement Object with 2 security definitions?

**Comment by webron** [comment]
Try:

```yaml
paths:
  '/endpoint/':
    security:
     - securityDefinitionA: []
       securityDefinitionB: []
     - securityDefinitionC: []

securityDefinitions:
  securityDefinitionA:
    type: apiKey
    name: X-HeaderA
    in: header
  securityDefinitionB:
    type: apiKey
    name: X-HeaderB
    in: header
  securityDefinitionC:
    type: apiKey
    name: X-HeaderC
    in: header
```
