### ISSUE TITLE
Broken validation for path parameters

### ISSUE THREAD

**Issue by wolli2710** [swagger-api/swagger-editor#841]
I have a basePath that includes the parameter user_id. When I write down the parameter an error occurs which says the parameter is not declared, when it is... but in the basePath.

In the Error view you can see:
Path parameter is defined but is not declared: user_id

```
basePath: /v1/users/{user_id}

paths:
  /event:
    post:
      description: |
        Creates a `event` object.
      parameters:
      - name: user_id
        in: path
        required: true
        type: number
        format: integer
```
