### ISSUE TITLE
apiKey Authenticate button broken

### ISSUE THREAD

**Issue by jt000** [swagger-api/swagger-editor#862]
Looks like the latest merge caused a regression in the "Security -> Authenticate" button. This worked on 4/10/2016.

Clicking on the Security->Authenticate button throws the following error:
```
bundle.js:33 Error: [$injector:unpr] Unknown provider: tProvider <- t
http://errors.angularjs.org/1.5.3/$injector/unpr?p0=tProvider%20%3C-%20t
    at bundle.js:32
    at bundle.js:32
    at Object.r [as get] (bundle.js:32)
    at bundle.js:32
    at r (bundle.js:32)
    at i (bundle.js:32)
    at Object.a [as invoke] (bundle.js:32)
    at h.instance (bundle.js:33)
    at bundle.js:80
    at s (bundle.js:34)(anonymous function) @ bundle.js:33
```

My `securityDefinitions` looks like this:

```
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
```
