### ISSUE TITLE
Suggestion: Add a warning for undefined enum type?

### ISSUE THREAD

**Issue by icefoxen** [swagger-api/swagger-editor#891]
Following from this issue: https://github.com/swagger-api/swagger-codegen/issues/2700

If you have a data type definition with an enum in it, such as:

``` yaml
  TaskResult:
    type: object
      status:
        description: The current state of the task
        enum:
          - PENDING
          - RUNNING
          - COMPLETE
          - FAILED
```

The JSON schema spec allows the values of the enum to be any type, but it appears at least one code generator breaks unless you add a `type:` line to the status field as well.  Is it worth it to make the editor output a warning when you don't specify a type for an enum?
