### ISSUE TITLE
Automatically add path params if path contains path params when typing in a new path

### ISSUE THREAD

**Issue by mohsen1** [swagger-api/swagger-editor#96]
For example, typing `/{user}:` will get autocompleted to:

``` yaml
  /{user}:
    parameters:
      - name: user
        in: path
        description: user path parameter
        type: string
```
