### ISSUE TITLE
When importing, relative $ref are not resolved

### ISSUE THREAD

**Issue by marcopiraccini** [swagger-api/swagger-editor#975]
```yaml
            "schema": {
              "$ref": "./mydef.json"
            }
```

* Swagger Editor version(from Help > About menu): Version 2.10.1
* My browser: Firefox

**Issue**
I want to import a swagger using import in URL. 
This swagger has relative $ref, but are not resolved. Indeed for every $ref I have the error: 
 `✖ Swagger Error Reference could not be resolved: ./mydef.json`
